/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coreui;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int coordinatorLayoutStyle = 0x7f020064;
        public static final int font = 0x7f020079;
        public static final int fontProviderAuthority = 0x7f02007b;
        public static final int fontProviderCerts = 0x7f02007c;
        public static final int fontProviderFetchStrategy = 0x7f02007d;
        public static final int fontProviderFetchTimeout = 0x7f02007e;
        public static final int fontProviderPackage = 0x7f02007f;
        public static final int fontProviderQuery = 0x7f020080;
        public static final int fontStyle = 0x7f020081;
        public static final int fontVariationSettings = 0x7f020082;
        public static final int fontWeight = 0x7f020083;
        public static final int keylines = 0x7f020093;
        public static final int layout_anchor = 0x7f020095;
        public static final int layout_anchorGravity = 0x7f020096;
        public static final int layout_behavior = 0x7f020097;
        public static final int layout_dodgeInsetEdges = 0x7f0200c1;
        public static final int layout_insetEdge = 0x7f0200ca;
        public static final int layout_keyline = 0x7f0200cb;
        public static final int statusBarBackground = 0x7f020106;
        public static final int ttcIndex = 0x7f020139;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f030000;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f04003f;
        public static final int notification_icon_bg_color = 0x7f040040;
        public static final int ripple_material_light = 0x7f04004a;
        public static final int secondary_text_default_material_light = 0x7f04004c;
    }
    public static final class dimen {
        private dimen() {}

        public static final int